//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topicos.WWI.Customers.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization; 
    [DataContract] public partial class Cities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cities()
        {
            this.Customers = new HashSet<Customers>();
            this.Customers1 = new HashSet<Customers>();
        }
    
        [DataMember] public int CityID { get; set; }
        [DataMember] public string CityName { get; set; }
        [DataMember] public int StateProvinceID { get; set; }
        [DataMember] public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        [DataMember] public Nullable<long> LatestRecordedPopulation { get; set; }
        [DataMember] public int LastEditedBy { get; set; }
        [DataMember] public System.DateTime ValidFrom { get; set; }
        [DataMember] public System.DateTime ValidTo { get; set; }
    
        public virtual People People { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers1 { get; set; }
    }
}
