//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topicos.WWI.Customers.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization; 
    [DataContract] public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Customers1 = new HashSet<Customers>();
        }
    
        [DataMember] public int CustomerID { get; set; }
        [DataMember] public string CustomerName { get; set; }
        [DataMember] public int BillToCustomerID { get; set; }
        [DataMember] public int CustomerCategoryID { get; set; }
        [DataMember] public Nullable<int> BuyingGroupID { get; set; }
        [DataMember] public int PrimaryContactPersonID { get; set; }
        [DataMember] public Nullable<int> AlternateContactPersonID { get; set; }
        [DataMember] public int DeliveryMethodID { get; set; }
        [DataMember] public int DeliveryCityID { get; set; }
        [DataMember] public int PostalCityID { get; set; }
        [DataMember] public Nullable<decimal> CreditLimit { get; set; }
        [DataMember] public System.DateTime AccountOpenedDate { get; set; }
        [DataMember] public decimal StandardDiscountPercentage { get; set; }
        [DataMember] public bool IsStatementSent { get; set; }
        [DataMember] public bool IsOnCreditHold { get; set; }
        [DataMember] public int PaymentDays { get; set; }
        [DataMember] public string PhoneNumber { get; set; }
        [DataMember] public string FaxNumber { get; set; }
        [DataMember] public string DeliveryRun { get; set; }
        [DataMember] public string RunPosition { get; set; }
        [DataMember] public string WebsiteURL { get; set; }
        [DataMember] public string DeliveryAddressLine1 { get; set; }
        [DataMember] public string DeliveryAddressLine2 { get; set; }
        [DataMember] public string DeliveryPostalCode { get; set; }
        [DataMember] public System.Data.Entity.Spatial.DbGeography DeliveryLocation { get; set; }
        [DataMember] public string PostalAddressLine1 { get; set; }
        [DataMember] public string PostalAddressLine2 { get; set; }
        [DataMember] public string PostalPostalCode { get; set; }
        [DataMember] public int LastEditedBy { get; set; }
        [DataMember] public System.DateTime ValidFrom { get; set; }
        [DataMember] public System.DateTime ValidTo { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Cities Cities1 { get; set; }
        public virtual DeliveryMethods DeliveryMethods { get; set; }
        public virtual People People { get; set; }
        public virtual People People1 { get; set; }
        public virtual People People2 { get; set; }
        public virtual BuyingGroups BuyingGroups { get; set; }
        public virtual CustomerCategories CustomerCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers1 { get; set; }
        public virtual Customers Customers2 { get; set; }
    }
}
