//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topicos.WWI.Customers.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization; 
    [DataContract] public partial class People
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public People()
        {
            this.Cities = new HashSet<Cities>();
            this.DeliveryMethods = new HashSet<DeliveryMethods>();
            this.People1 = new HashSet<People>();
            this.BuyingGroups = new HashSet<BuyingGroups>();
            this.CustomerCategories = new HashSet<CustomerCategories>();
            this.Customers = new HashSet<Customers>();
            this.Customers1 = new HashSet<Customers>();
            this.Customers2 = new HashSet<Customers>();
        }
    
        [DataMember] public int PersonID { get; set; }
        [DataMember] public string FullName { get; set; }
        [DataMember] public string PreferredName { get; set; }
        [DataMember] public string SearchName { get; set; }
        [DataMember] public bool IsPermittedToLogon { get; set; }
        [DataMember] public string LogonName { get; set; }
        [DataMember] public bool IsExternalLogonProvider { get; set; }
        [DataMember] public byte[] HashedPassword { get; set; }
        [DataMember] public bool IsSystemUser { get; set; }
        [DataMember] public bool IsEmployee { get; set; }
        [DataMember] public bool IsSalesperson { get; set; }
        [DataMember] public string UserPreferences { get; set; }
        [DataMember] public string PhoneNumber { get; set; }
        [DataMember] public string FaxNumber { get; set; }
        [DataMember] public string EmailAddress { get; set; }
        [DataMember] public byte[] Photo { get; set; }
        [DataMember] public string CustomFields { get; set; }
        [DataMember] public string OtherLanguages { get; set; }
        [DataMember] public int LastEditedBy { get; set; }
        [DataMember] public System.DateTime ValidFrom { get; set; }
        [DataMember] public System.DateTime ValidTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cities> Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryMethods> DeliveryMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<People> People1 { get; set; }
        public virtual People People2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyingGroups> BuyingGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCategories> CustomerCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers2 { get; set; }
    }
}
